- name: teste
  hosts: all
  
  vars_prompt:
   - name: "some_password"
     prompt: "Enter password"
     private: yes
     
   - name: "my_password2"
     prompt: "Enter password2"
     private: yes
     encrypt: "md5_crypt"
     confirm: yes
     salt_size: 7
     salt: "foo"
     
  tasks:
   - name: look we crypted a password
     shell: echo my password is {{my_password2}}
