---
- hosts: localhost
  tasks:
  - name: Install Windows updates
    win_updates:
    state: installed
    register: reboot

  - name: Reboot if necessary
    win_reboot:
    when: register.reboot_required
